FROM golang:1.22.1

ENV CGO_ENABLED 0

WORKDIR /app

COPY . .

RUN wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

RUN go mod download

RUN go build main.go

RUN useradd -u 2000 product
USER product

EXPOSE 8080

CMD ["./main"]
